name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Vars
      run: echo "val process = { env: { EMAIL_SERVICE_ID: '${{ environments.EMAIL_SERVICE_ID }}', EMAIL_TEMPLATE_ID: '${{ environments.EMAIL_TEMPLATE_ID }}' EMAIL_PUBLIC_KEY: '${{ secrets.EMAIL_PUBLIC_KEY }}'" >> envs.js
      # env:
      #   EMAIL_PUBLIC_KEY: ${{ secrets.EMAIL_PUBLIC_KEY }}
      #   EMAIL_SERVICE_ID: ${{ environments.EMAIL_SERVICE_ID }}
      #   EMAIL_TEMPLATE_ID: ${{ environments.EMAIL_TEMPLATE_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
