name: CI

on:
    push:
        branches:
            - main
jobs:
    # Build job
    build:
        environment: github-pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v3
            - name: Log stuff
              run: echo ${{ vars.EMAIL_TEMPLATE_ID }}
            - name: Inject Keys
              env:
                  EMAIL_SERVICE_ID: ${{ vars.EMAIL_SERVICE_ID }}
                  EMAIL_TEMPLATE_ID: ${{ vars.EMAIL_TEMPLATE_ID }}
                  EMAIL_PUBLIC_KEY: ${{ secrets.EMAIL_PUBLIC_KEY }}
              run: echo "const EMAIL_SERVICE_ID = '$EMAIL_SERVICE_ID'; const EMAIL_TEMPLATE_ID = '$EMAIL_TEMPLATE_ID'; const EMAIL_PUBLIC_KEY = '$EMAIL_PUBLIC_KEY';" >> envs.js
            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                  source: ./
                  destination: ./_site
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3

    # Deployment job
    deploy:
        permissions:
            contents: read
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
